name: Test Audit
on: [push, pull_request]

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build Dockerfile.base
      run: docker build . --file Dockerfile.base --tag jakejarvis/chrome-headless:latest
    - name: Run audit on https://github.com/
      uses: ./
      with:
        url: 'https://github.com/'
      id: lighthouse
    - name: Comment output on PR
      if: github.event_name == 'pull_request'
      uses: unsplash/comment-on-pr@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        msg: "Here is your Lighthouse score:\n
        \n
        Performance: ${{ steps.lighthouse.outputs.performance }}\n
        Accessibility: ${{ steps.lighthouse.outputs.accessibility }}\n
        Best Practices: ${{ steps.lighthouse.outputs.practices }}\n
        SEO: ${{ steps.lighthouse.outputs.seo }}\n
        PWA: ${{ steps.lighthouse.outputs.pwa }}\n"
    - uses: actions/upload-artifact@master
      with:
        name: report
        path: './report'
